apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learnfast
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stefcho69/smes-learnfast.git
    targetRevision: main
    path: learnfast-infra/k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: learnfast
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
